specs: add how commands requests/responses are sent to/from the device
Eideticom/eid-hermes pull request #10
Opened 2020-11-02 23:29 UTC by iomartin

Non-DMA command requests/responses will be written to BAR0 registers, at
offsets TBD. This is similar to how XDMA operates.

When non-XDMA commands complete, the device will raise an interrupt.

2020-11-02 23:30 UTC, iomartin commented
Note that some of the links here depend on #8 being merged

2020-11-04 17:46 UTC, sbates130272 requested changes
@iomartin a couple of minor changes.

2020-11-04 17:46 UTC, sbates130272 commented on specs/eid-hermes-theory-of-operation.md
> +Commands are defined on another [document][1], but they can be
s/on/in/

2020-11-04 17:46 UTC, sbates130272 commented on specs/eid-hermes-theory-of-operation.md
> +interrupt.
Add: The host can also choose to poll the relevant BAR0 register to check for command completion.

2020-11-04 18:05 UTC, sbates130272 approved these changes

2020-11-04 18:05 UTC, merged