Increase slot-offsets to 64-bits
Eideticom/eid-hermes pull request #40
Opened 2022-04-26 11:17 UTC by niclashedam

This resolves the 64-bit issue of #39.
Mind that this should trigger an increase of `EHVER` as it is not compatible with previous versions.

2022-09-28 20:56 UTC, iomartin commented
This is fine, but can you update the QEMU model as well and bump the version please?

2022-09-29 09:41 UTC, niclashedam commented
I have updated the QEMU model and bumped it to version 2. Should we make a document describing the version differences?

2022-10-04 22:27 UTC, iomartin commented
I tried running this with PR https://github.com/Eideticom/eid-hermes-qemu/pull/14 (which currently points to https://github.com/niclashedam/eid-hermes-qemu/commit/56700c84f61f5d16053f1259363693e8f7088603).

I had some compilation warnings (below), but more importantly, it's failing some tests:

```
hermes@hermes-vm:~/eid-hermes$ sudo tests/unit_test -v          
testInvalidFlags (__main__.DriverTests) ... ok       
testInvalidIoctlNum (__main__.DriverTests) ... ok
testLargeProgram (__main__.DriverTests) ... ok
testReadBeforeProg (__main__.DriverTests) ... ok
testReadBeforeWrite (__main__.DriverTests) ... ok                     
testReadLargeOffset (__main__.DriverTests) ... ok
testReadOffset (__main__.DriverTests) ... FAIL                        
testReadTooLarge (__main__.DriverTests) ... FAIL
testReadvFlagNotSupported (__main__.DriverTests) ... FAIL
testSendProgram (__main__.DriverTests) ... ok        
testTooManyPrograms (__main__.DriverTests) ... ok   
testWriteBeforeProg (__main__.DriverTests) ... ok             
testWriteLargeOffset (__main__.DriverTests) ... ok   
testWriteOffset (__main__.DriverTests) ... FAIL
testWriteReadLarge (__main__.DriverTests) ... FAIL
testWriteReadMedium (__main__.DriverTests) ... FAIL
testWriteReadSmall (__main__.DriverTests) ... FAIL                    
testWriteReadZero (__main__.DriverTests) ... ok
testWriteReadv (__main__.DriverTests) ... FAIL                        
testWriteReadvOneReadBuffer (__main__.DriverTests) ... FAIL
testWriteReadvOneWriteBuffer (__main__.DriverTests) ... FAIL
testWriteTooLarge (__main__.DriverTests) ... FAIL
testWritevFlagNotSupported (__main__.DriverTests) ... ok

======================================================================
FAIL: testReadOffset (__main__.DriverTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/unit_test", line 105, in testReadOffset
    self._testWriteRead(self.payloadSmall, roff=1024)
  File "tests/unit_test", line 60, in _testWriteRead
    self._testWriteReadv([payload], rbuffs, rsize, woff, roff)
  File "tests/unit_test", line 52, in _testWriteReadv
    self.assertEqual(ret, wsize)
AssertionError: 0 != 256

======================================================================
FAIL: testReadTooLarge (__main__.DriverTests)
----------------------------------------------------------------------
AssertionError: 0 != 256

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tests/unit_test", line 114, in testReadTooLarge
    self._testWriteRead(self.payloadSmall, rsize=2*self.ehdssze)
AssertionError: "1048576 != 2097152" does not match "0 != 256"

======================================================================
FAIL: testReadvFlagNotSupported (__main__.DriverTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/unit_test", line 166, in testReadvFlagNotSupported
    self._testWriteReadv(payloads, rbuffs, rflags=os.RWF_NOWAIT)
  File "tests/unit_test", line 52, in _testWriteReadv
    self.assertEqual(ret, wsize)
AssertionError: 0 != 256

======================================================================
FAIL: testWriteOffset (__main__.DriverTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/unit_test", line 102, in testWriteOffset
    self._testWriteRead(self.payloadSmall, woff=1024)
  File "tests/unit_test", line 60, in _testWriteRead
    self._testWriteReadv([payload], rbuffs, rsize, woff, roff)
  File "tests/unit_test", line 54, in _testWriteReadv
    self.assertEqual(ret, rsize)
AssertionError: 0 != 256

======================================================================
FAIL: testWriteReadLarge (__main__.DriverTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/unit_test", line 99, in testWriteReadLarge
    self._testWriteRead(self.payloadLarge)
  File "tests/unit_test", line 60, in _testWriteRead
    self._testWriteReadv([payload], rbuffs, rsize, woff, roff)
  File "tests/unit_test", line 52, in _testWriteReadv
    self.assertEqual(ret, wsize)
AssertionError: 0 != 1048576

======================================================================
FAIL: testWriteReadMedium (__main__.DriverTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/unit_test", line 96, in testWriteReadMedium
    self._testWriteRead(self.payloadMedium)
  File "tests/unit_test", line 60, in _testWriteRead
    self._testWriteReadv([payload], rbuffs, rsize, woff, roff)
  File "tests/unit_test", line 52, in _testWriteReadv
    self.assertEqual(ret, wsize)
AssertionError: 0 != 4096

======================================================================
FAIL: testWriteReadSmall (__main__.DriverTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/unit_test", line 93, in testWriteReadSmall
    self._testWriteRead(self.payloadSmall)
  File "tests/unit_test", line 60, in _testWriteRead
    self._testWriteReadv([payload], rbuffs, rsize, woff, roff)
  File "tests/unit_test", line 52, in _testWriteReadv
    self.assertEqual(ret, wsize)
AssertionError: 0 != 256

======================================================================
FAIL: testWriteReadv (__main__.DriverTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/unit_test", line 140, in testWriteReadv
    self._testWriteReadv(payloads, rbuffs)
  File "tests/unit_test", line 52, in _testWriteReadv
    self.assertEqual(ret, wsize)
AssertionError: 0 != 4352

======================================================================
FAIL: testWriteReadvOneReadBuffer (__main__.DriverTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/unit_test", line 152, in testWriteReadvOneReadBuffer
    self._testWriteReadv(payloads, rbuffs)
  File "tests/unit_test", line 52, in _testWriteReadv
    self.assertEqual(ret, wsize)
AssertionError: 0 != 4352

======================================================================
FAIL: testWriteReadvOneWriteBuffer (__main__.DriverTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/unit_test", line 146, in testWriteReadvOneWriteBuffer
    self._testWriteReadv(payloads, rbuffs)
  File "tests/unit_test", line 52, in _testWriteReadv
    self.assertEqual(ret, wsize)
AssertionError: 0 != 256

======================================================================
FAIL: testWriteTooLarge (__main__.DriverTests)
----------------------------------------------------------------------
AssertionError: 0 != 2097152

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tests/unit_test", line 110, in testWriteTooLarge
    self._testWriteRead(payload)
AssertionError: "1048576 != 2097152" does not match "0 != 2097152"

----------------------------------------------------------------------
Ran 23 tests in 0.024s

FAILED (failures=11)
```

Compilation warnings:

```
   CC [M]  /home/hermes/eid-hermes/src/driver/hermes_cdev.o
/home/hermes/eid-hermes/src/driver/hermes_cdev.c: In function ‘hermes_read_cfg’:
<command-line>: warning: format ‘%x’ expects argument of type ‘unsigned int’, but argument 9 has type ‘uint64_t’ {aka ‘long long unsigned int’} [-Wformat=]
/home/hermes/eid-hermes/src/driver/hermes_cdev.c:25:21: note: in expansion of macro ‘KBUILD_MODNAME’
   25 | #define pr_fmt(fmt) KBUILD_MODNAME ":%s: " fmt, __func__
      |                     ^~~~~~~~~~~~~~
./include/linux/dynamic_debug.h:125:15: note: in expansion of macro ‘pr_fmt’
  125 |   func( [...]

2022-10-12 15:45 UTC, iomartin requested changes
@niclashedam Can you fix the compilation warnings please? Otherwise this looks good to me

2022-10-13 13:04 UTC, niclashedam commented
Yep. Working on it. I have a tight schedule currently, and I have trouble compiling QEMU. It can't find libubpf, so I have to figure that out as well. I'll let you know when they are resolved.

2022-10-14 11:32 UTC, niclashedam commented
```
.......................
----------------------------------------------------------------------
Ran 23 tests in 0.031s

OK
```

And compilation errors resolved 🎆

2022-10-14 15:18 UTC, iomartin reviewed
See one nit below. Otherwise looks good.

The failing tests were fixed by https://github.com/Eideticom/eid-hermes-qemu/pull/17, if you were running the latest master you wouldn't see them.

2022-10-14 15:18 UTC, iomartin commented on src/driver/hermes_cdev.c
> +ehpssze: 0x%x ehdsoff: 0x%llx ehdssze: 0x%x\n",
nit: this is not properly aligned

2022-10-15 12:34 UTC, niclashedam commented
Nit fixed. And I tested on the rebased https://github.com/Eideticom/eid-hermes-qemu/pull/14, which explains why all tests were OK for me.

2025-11-14 18:35 UTC, closed without merging